[project]
name = "news_podcast"
version = "0.1.0"
description = "news-podcast using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.102.0,<1.0.0"
]

[project.scripts]
news_podcast = "news_podcast.main:run"
run_crew = "news_podcast.main:run"
train = "news_podcast.main:train"
replay = "news_podcast.main:replay"
test = "news_podcast.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
